# From https://github.com/zmkfirmware/unified-zmk-config-template/blob/main/build.yaml
# board: [ "nice_nano_v2" ]
# shield: [ "0_sixty" ]

include:
 - board: seeeduino_xiao
   shield: hummingbird
   snippet: studio-rpc-usb-uart
   cmake-args: -DCONFIG_ZMK_STUDIO=y


