# From https://github.com/zmkfirmware/unified-zmk-config-template/blob/main/build.yaml
board: [ "nice_nano_v2" ]
shield: [ "0_sixty" ]

#include:
#  - board: nice_nano_v2
#    shield: 0_sixty
#    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"0-SIXTY\"
#    artifact-name: 0_sixty


